name: shopify_flutter
description: A Flutter package to seamlessly connect your Shopify store with your app.
version: 2.6.2
repository: https://github.com/imsujan276/shopify_flutter
issue_tracker: https://github.com/imsujan276/shopify_flutter/issues

tags:
  - shopify
  - shopify_flutter

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.7.1
  shared_preferences: ^2.0.20
  intl: ">=0.19.0 <0.21.2"
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # dart run build_runner watch --delete-conflicting-outputs
  build_runner: ^2.3.3
  freezed: ^3.2.3
  analyzer: ^8.3.0

screenshots:
  - description: "Search Example of the shopify storefront"
    path: example/screenshot/search.png
